<template>
  <lin-alert icon="search" type="success" title="提示文案"></lin-alert>
  <lin-alert
    class="mt-20"
    icon="email"
    type="info"
    title="提示文案"
  ></lin-alert>
  <lin-alert
    class="mt-20"
    icon="delete"
    type="warning"
    title="提示文案"
  ></lin-alert>
  <lin-alert
    class="mt-20"
    icon="upload"
    type="danger"
    title="提示文案"
  ></lin-alert>
</template>
